spring.application.name=restaurant-management

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=RestaurantManager;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# T?t auto convert camelCase ? snake_case
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


jwt.secretKey= TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
jwt.expiration= 3600
api.prefix=/api

momo.partner-code=MOMO
momo.return-url=http://localhost:3000/payment-Success
momo.end-point=https://test-payment.momo.vn/v2/gateway/api
momo.ipn-url=http://localhost:8080/api/momo/ipn-handler
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.request-type=captureWallet

# ===============================
# C?U HÌNH VNPAY (Sandbox)
# ===============================
vnpay.tmn-code=Y28O5VZD
vnpay.hash-secret=2O9UT8G9IU20FPX2TE2081NHAKK5QF5D
vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3000/payment-success
vnpay.ipn-url=http://localhost:8080/api/vnpay/ipn-handler
vnpay.version=2.1.0
vnpay.command=pay
vnpay.currency=VND
vnpay.locale=vn


logging.level.org.springframework.security=DEBUG


